create table if not exists public.video_prompts (
  id bigint generated by default as identity primary key,
  title text not null,
  platform text not null,
  category text not null,
  prompt text not null,
  thumbnail_url text not null,
  video_url text,
  difficulty text not null,
  tags text[] not null default '{}',
  likes integer not null default 0,
  created_at date not null default current_date
);

alter table public.video_prompts enable row level security;

drop policy if exists "Video prompts are viewable by everyone" on public.video_prompts;
drop policy if exists "Authenticated users can create video prompts" on public.video_prompts;
drop policy if exists "Authenticated users can update video prompts" on public.video_prompts;
drop policy if exists "Authenticated users can delete video prompts" on public.video_prompts;

create policy "Video prompts are viewable by everyone"
  on public.video_prompts
  for select
  using (true);

create policy "Authenticated users can create video prompts"
  on public.video_prompts
  for insert
  to authenticated
  with check (true);

create policy "Authenticated users can update video prompts"
  on public.video_prompts
  for update
  to authenticated
  using (true)
  with check (true);

create policy "Authenticated users can delete video prompts"
  on public.video_prompts
  for delete
  to authenticated
  using (true);
